INPUT_DEVICE = 22
OUTPUT_DEVICE = 18

SAMPLE_RATE = 48000
CHANNELS = 1

# Bit crusher
BIT_CRUSHER_ENABLE = 0
BIT_CRUSHER_BIT_DEPTH = 64
BIT_CRUSHER_DOWNSAMPLE = 1

# Gain
GAIN_ENABLE = 1
GAIN_MULTIPLIER = 1.0

# Distortion
DISTORTION_ENABLE = 0
DISTORTION_MULTIPLIER = 1.0

# Reverb
REVERB_ENABLE = 0
REVERB_MIX = 0.30

# Noise Clip
NOISE_CLIP_ENABLE = 1
NOISE_CLIP_THRESHOLD = 0.02
